services:

    # command chains holder
    nimias_chain_command.registry:
        class: Nimias\ChainCommandBundle\Service\CommandChainsRegistry

    # command chains processor
    nimias_chain_command.processor:
        class: Nimias\ChainCommandBundle\Service\CommandEventsSubscriber
        arguments:
            - "@nimias_chain_command.registry"
            - "@=container.has('logger') ? service('logger') : null"
        tags:
            - { name: kernel.event_subscriber }